version: "2.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - ${NGINX_PROXY_PORT}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - server

  nginx:
    image: nginx:1.11
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    depends_on:
      - php
    networks:
      - server
    environment:
      - VIRTUAL_HOST=laravel.dev,*.laravel.dev

  php:
    image: zurbaev/php71-common
    expose:
      - 9000
    volumes:
      - "${APP_DIR}:/var/www/html"
    depends_on:
      - mysql
    networks:
      - database
      - server

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  redis:
    image: redis:3.0
    networks:
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - database

  dashboard:
    image: zurbaev/php71-dashboard
    volumes:
      - "${APP_DIR}:/var/www/html"
    networks:
      - database
      - server

networks:
  database:
  server: